[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "PhamTrungVinh", email = "phamtrungvinh2020@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "deepeval>=4.1.5",
    "fastapi>=0.141.1",
    "langchain-google-vertexai>=3.2.4",
    "langchain-openai>=1.4.1",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "langsmith>=0.10.16",
    "ragas>=0.4.3",
    "streamlit>=1.61.1",
    "torchvision>=0.28.0",
    "uvicorn>=0.52.1",
]

[project.scripts]
project = "project:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
