"""Initial event service schema.

Revision ID: event_0001
"""

from alembic import op
import sqlalchemy as sa

revision = "event_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_inbox',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('envelope_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_inbox')
    # ### end Alembic commands ###
