"""Initial memory service schema.

Revision ID: memory_0001
"""

from alembic import op
import sqlalchemy as sa

revision = "memory_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodic_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodic_memory_expires_at'), 'episodic_memory', ['expires_at'], unique=False)
    op.create_index(op.f('ix_episodic_memory_id'), 'episodic_memory', ['id'], unique=False)
    op.create_index(op.f('ix_episodic_memory_owner_id'), 'episodic_memory', ['owner_id'], unique=False)
    op.create_index(op.f('ix_episodic_memory_thread_id'), 'episodic_memory', ['thread_id'], unique=False)
    op.create_table('semantic_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_memory_expires_at'), 'semantic_memory', ['expires_at'], unique=False)
    op.create_index(op.f('ix_semantic_memory_id'), 'semantic_memory', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_memory_owner_id'), 'semantic_memory', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_memory_owner_id'), table_name='semantic_memory')
    op.drop_index(op.f('ix_semantic_memory_id'), table_name='semantic_memory')
    op.drop_index(op.f('ix_semantic_memory_expires_at'), table_name='semantic_memory')
    op.drop_table('semantic_memory')
    op.drop_index(op.f('ix_episodic_memory_thread_id'), table_name='episodic_memory')
    op.drop_index(op.f('ix_episodic_memory_owner_id'), table_name='episodic_memory')
    op.drop_index(op.f('ix_episodic_memory_id'), table_name='episodic_memory')
    op.drop_index(op.f('ix_episodic_memory_expires_at'), table_name='episodic_memory')
    op.drop_table('episodic_memory')
    # ### end Alembic commands ###
